<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0-next.6 ./static/FreeBrain.glb
-->

<script lang="ts">
	import { T } from "@threlte/core";
	import { useGltf } from "@threlte/extras";
	import { onMount } from "svelte";
	import type { Group, Object3DEventMap } from "three";

	type Props = {
		ref?: Group<Object3DEventMap>;
		[key: string]: any;
	};
	let { ref = $bindable(), ...props }: Props = $props();

	const gltf = useGltf("/FreeBrain.glb");

	onMount(() => {
		// console.log(
		// 	gltf.then((d) => {
		// 		console.log(d);
		// 	}),
		// );
	});

	function log(d: any) {
		// d.materials[""].wireframe = true;
		// console.log(d.materials[""].wireframe);

		// console.log(d.materials[""].color);

		console.log(d);
	}
</script>

<T.Group bind:ref dispose={false} {...props}>
	{#await gltf then gltf}
		<!-- {log(gltf)} -->
		<T.Mesh geometry={gltf.nodes.Brain.geometry} wireframe material.wireframe={true} material.color={"#009ead"} transparent={true} opacity={0.25} material.opacity={0.01} />
	{/await}
</T.Group>
